# Global
timepoints: ['baseline_year_1_arm_1']

# Behavioral
sst_behavioral_path: "../../data/01_raw/tabular/core/imaging/mri_y_tfmr_sst_beh.csv"
nback_behavioral_path: "../../data/01_raw/tabular/core/imaging/mri_y_tfmr_nback_beh.csv"
rdex_map_path: "../../data/01_raw/SST_MAPS_base_r3.csv"
rdex_map_notf_path: "../../data/01_raw/baseline_notf_SST_MAPS.csv"
# nback_rdex_median_path: "../../data/01_raw/abcd_efu_base_inf_postmedians.csv"
nback_rdex_map_0back: "../../data/01_raw/zeroback_MAPS_baseline.csv"
nback_rdex_map_2back: "../../data/01_raw/twoback_MAPS_baseline.csv"
filtered_behavioral_path_sst: "../../data/03_primary/filtered_behavioral.csv"
filtered_behavioral_no_tf_path_sst: "../../data/03_primary/filtered_behavioral_no_tf.csv"
filtered_behavioral_path_nback: "../../data/03_primary/filtered_behavioral_nback.csv"

beh_rt_vars: {
    'tfmri_sst_all_beh_crgo_mrt': 'correct_go_mrt',
    'tfmri_sst_all_beh_crgo_stdrt': 'correct_go_stdrt',
    'tfmri_sst_all_beh_total_issrt': 'issrt'
}

nback_rt_vars: {
    "tfmri_nb_all_beh_ctotal_mrt": "nback_mrt",
    "tfmri_nb_all_beh_ctotal_stdrt": "nback_stdrt",
}

# MRI
sst_r1_dof_path_r5: "../../data/01_raw/abcd-sync/5.0/tabulated/img/mrisstr1bw01.csv"
sst_r2_dof_path_r5: "../../data/01_raw/abcd-sync/5.0/tabulated/img/mrisstr2bw01.csv"

nback_r1_dof_path_r5: "../../data/01_raw/abcd-sync/5.0/tabulated/img/nbackr101.csv"
nback_r2_dof_path_r5: "../../data/01_raw/abcd-sync/5.0/tabulated/img/nbackr201.csv"

sst_r1_dof_path_r6: "../../data/01_raw/abcd-sync/6.0/tabulated/img/mrisstr1bw01.csv"
sst_r2_dof_path_r6: "../../data/01_raw/abcd-sync/6.0/tabulated/img/mrisstr2bw01.csv"

nback_r1_dof_path_r6: "../../data/01_raw/abcd-sync/6.0/tabulated/img/nbackr101.csv"
nback_r2_dof_path_r6: "../../data/01_raw/abcd-sync/6.0/tabulated/img/nbackr201.csv"

# vol_info_path_r4: "../../data/02_intermediate/betas/r4/vol_info.parquet"
vol_info_path_r5: "../../data/02_intermediate/betas/r5/vol_info.parquet"
vol_info_path_r6: "../../data/02_intermediate/betas/r6/vol_info.parquet"
mri_qc_path: "../../data/01_raw/tabular/core/imaging/mri_y_qc_incl.csv"

sst_conditions: {
    'cs': 'correct_stop',
    'cg': 'correct_go',
    'is': 'incorrect_stop',
    'ig': 'incorrect_go'
}

nback_conditions: {
    '2b': '2back',
    '0b': '0back'
}

runs: ['r01', 'r02']
hemispheres: ['lh', 'rh']

roi_base_path: "../../data/01_raw/tabular/core/imaging/"

sst_csvcg_names: ['correct.stop.vs.correct.go_']
sst_cgvfx_names: ['correct.go.vs.fixation_']
sst_isvcg_names: ['incorrect.stop.vs.correct.go_']
sst_igvcg_names: ['incorrect.go.vs.correct.go_']


# cleaned betas
mri_path_r5: "../../data/01_raw/abcd-sync/5.0/processed/vertexwise/SST/sst_regressors/"

# beta_input_dir_r4: "../../data/02_intermediate/betas/r4/"
beta_input_dir_r5: "../../data/02_intermediate/betas/r5/"
beta_input_dir_r6: "../../data/02_intermediate/betas/r6/"
beta_output_dir_r5: "../../data/02_intermediate/avg_betas/r5/"
beta_output_dir_r6: "../../data/02_intermediate/avg_betas/r6/"
processed_beta_dir_r5: "../../data/03_primary/processed_betas/r5/"
processed_beta_dir_r6: "../../data/03_primary/processed_betas/r6/"

motion_path: "../../data/01_raw/abcd-sync/6.0/tabulated/img/mriqcrp203.csv"
scanner_path: "../../data/01_raw/abcd-sync/6.0/tabulated/img/abcd_mri01.csv"
mri_confounds_output_dir: "../../data/03_primary/"

roi_betas_output_dir: "../../data/03_primary/roi_betas.parquet"

# Phenotype

phenotype_base_dir: "../../data/01_raw/tabular/core/"
phenotype_output_dir: "../../data/03_primary/"
phenotype_keywords:
    - bisbas
    - cbcl
    - eatq
    - nihtb
    - poa
    - bpm
    - upps

phenotype_vars:

    # Behavior Inhibition/Activation Scale
    bisbas_vars: {
        'bis_y_ss_bis_sum': 'bisbas_bis',
        'bis_y_ss_bism_sum': 'bisbas_bis_mod',
        'bis_y_ss_bas_rr': 'bisbas_reward',
        'bis_y_ss_basm_rr': 'bisbas_reward_mod',
        'bis_y_ss_bas_drive': 'bisbas_drive',
        'bis_y_ss_basm_drive': 'bisbas_drive_mod',
        'bis_y_ss_bas_fs': 'bisbas_fun'
    }

    # Urgency, (Lack of) Premeditation, (Lack of) Perserverence, and Sensation seeking
    upps_vars: {
        'upps_y_ss_negative_urgency': 'upps_neg_urgency',
        'upps_y_ss_lack_of_planning': 'upps_lack_planning',
        'upps_y_ss_sensation_seeking': 'upps_sensation_seeking',
        'upps_y_ss_positive_urgency': 'upps_positive_urgency',
        'upps_y_ss_lack_of_perseverance': 'upps_lack_perseverance'
    }


    nihtb_vars: {
        'nihtbx_fluidcomp_uncorrected': 'nihtb_fluidcomp_uncorr', # Cognition fluid composite
        'nihtbx_cryst_uncorrected': 'nihtb_crystallized_uncorr',
        'nihtbx_totalcomp_uncorrected': 'nihtb_totalcomp_uncorr',
        'nihtbx_picvocab_uncorrected': 'nihtb_picvocab_uncorr',
        'nihtbx_flanker_uncorrected': 'nihtb_flanker_uncorr',
        'nihtbx_list_uncorrected': 'nihtb_list_uncorr',
        'nihtbx_cardsort_uncorrected': 'nihtb_cardsort_uncorr',
        'nihtbx_pattern_uncorrected': 'nihtb_pattern_uncorr',
        'nihtbx_picture_uncorrected': 'nihtb_picture_uncorr',
        'nihtbx_reading_uncorrected': 'nihtb_reading_uncorr'
    }


    # ASEBA
    # Child Behavior Checklist
    cbcl_vars: {
        'cbcl_scr_syn_anxdep_r': 'anxdep_cbcl_raw',
        'cbcl_scr_syn_withdep_r': 'withdep_cbcl_raw',
        'cbcl_scr_syn_somatic_r': 'somatic_cbcl_raw',
        'cbcl_scr_syn_social_r': 'social_cbcl_raw',
        'cbcl_scr_syn_thought_r': 'thought_cbcl_raw',
        'cbcl_scr_syn_attention_r': 'attention_cbcl_raw',
        'cbcl_scr_syn_rulebreak_r': 'rulebreak_cbcl_raw',
        'cbcl_scr_syn_aggressive_r': 'aggressive_cbcl_raw',
        'cbcl_scr_syn_internal_r': 'internal_cbcl_raw',
        'cbcl_scr_syn_external_r': 'external_cbcl_raw',
        'cbcl_scr_syn_totprob_r': 'totalprob_cbcl_raw',
        'cbcl_scr_dsm5_depress_r': 'depress_dsm5_cbcl_raw',
        'cbcl_scr_dsm5_anxdisord_r': 'anxdisord_dsm5_cbcl_raw',
        'cbcl_scr_dsm5_somaticpr_r': 'somaticprob_dsm5_cbcl_raw',
        'cbcl_scr_dsm5_adhd_r': 'adhd_dsm5_cbcl_raw',
        'cbcl_scr_dsm5_opposit_r': 'opposit_dsm5_cbcl_raw',
        'cbcl_scr_dsm5_conduct_r': 'conduct_dsm5_cbcl_raw',
        'cbcl_scr_07_sct_r': 'sct_cbcl_raw',
        'cbcl_scr_07_ocd_r': 'ocd_cbcl_raw',
        'cbcl_scr_07_stress_r': 'stress_cbcl_raw'
    }

    # brief problem monitor
    bpm_vars:  {
        'bpm_t_scr_attention_r': 'attention_bpmt_raw',
        'bpm_t_scr_internal_r': 'internal_bpmt_raw',
        'bpm_t_scr_external_r': 'external_bpmt_raw'
    }


demo_fpath: "../../data/01_raw/tabular/core/abcd-general/abcd_p_demo.csv"
demo_vars: {
    'demo_prnt_ed_v2': 'parent_education',
    'demo_prnt_income_v2': 'parent_income',
    'demo_sex_v2': 'sex'
}

general_fpath: "../../data/01_raw/tabular/core/abcd-general/abcd_y_lt.csv"
general_vars: {
    'interview_age': 'age',
    'site_id_l': 'site'
}
